enum ErrorCodes {
  PARSE_ERROR = "4001",
  REQUEST_VALIDATOR_ERROR = "4002",
  ENTITY_NOT_FOUND_ERROR = "4041",
  DUPLICATE_ENTITY_ERROR = "4221",
  UNEXPECTED_ERROR = "5001",
}

export default ErrorCodes;
